if [ -z "$TMUX" ]; then
  exec tmux new-session -A -s "$(hostname -s)/$(basename $(pwd))"
fi

# Enable Powerlevel10k instant prompt. Should stay close to the top of ~/.zshrc.
# Initialization code that may require console input (password prompts, [y/n]
# confirmations, etc.) must go above this block; everything else may go below.
if [[ -r "${XDG_CACHE_HOME:-$HOME/.cache}/p10k-instant-prompt-${(%):-%n}.zsh" ]]; then
  source "${XDG_CACHE_HOME:-$HOME/.cache}/p10k-instant-prompt-${(%):-%n}.zsh"
fi

FPATH="$(brew --prefix)/share/zsh/site-functions:${FPATH}"

# Source Prezto.
if [[ -s "${ZDOTDIR:-$HOME}/.zprezto/init.zsh" ]]; then
  source "${ZDOTDIR:-$HOME}/.zprezto/init.zsh"
fi

export FZF_DEFAULT_OPTS="--bind='ctrl-o:execute(vi {})+abort' --layout=reverse --border --info=inline --margin=2,4 --padding=1 --height=40%"
export PYTHONBREAKPOINT=pudb.set_trace
export MCFLY_KEY_SCHEME=vim
export MCFLY_FUZZY=2
export MCFLY_RESULTS=50
export MCFLY_INTERFACE_VIEW=TOP
export NODE_OPTIONS=--max_old_space_size=8192

# Needed for pyenv when installing older Pythons on Big Sur
export LDFLAGS="-L/opt/homebrew/opt/zlib/lib -L/opt/homebrew/opt/bzip2/lib"
export CPPFLAGS="-I/opt/homebrew/opt/zlib/include -I/opt/homebrew/opt/bzip2/include"

# Read in API keys
ENV_FILE="${HOME}/.env"
[ -f ${ENV_FILE} ] && source ${ENV_FILE}

# By default, ^S freezes terminal output and ^Q resumes it. Disable that so
# that those keys can be used for other things.
unsetopt flowcontrol

export EDITOR='nvim'
export VISUAL='nvim'
export SHELL='/opt/homebrew/bin/zsh'


if which assh > /dev/null; then
  alias ssh="assh wrapper ssh"
fi

DIRENV="${HOME}/src/dotfiles/completions/_direnv"
[ -f ${DIRENV} ] && source ${DIRENV}

AWS_ZSH_COMPLETER="${HOME}/.local/bin/aws_zsh_completer.sh"
[ -f ${AWS_ZSH_COMPLETER} ] && source ${AWS_ZSH_COMPLETER}

FZF_ZSH="${HOME}/.fzf.zsh"
[ -f ${FZF_ZSH} ] && source ${FZF_ZSH}

PDM="${HOME}/src/dotfiles/_pdm"
[ -f ${PDM} ] && source ${PDM}

ALIASES_LOCAL="${HOME}/.aliases.local"
[ -f ${ALIASES_LOCAL} ] && source ${ALIASES_LOCAL}

GIT_EXTRAS="/opt/homebrew/opt/git-extras/share/git-extras/git-extras-completion.zsh"
[ -f ${GIT_EXTRAS} ] && source ${GIT_EXTRAS}

ITERM2_SHELL_INTEGRATIONS="${HOME}/.iterm2_shell_integration.zsh"
[ -f ${ITERM2_SHELL_INTEGRATIONS} ] && source ${ITERM2_SHELL_INTEGRATIONS}

BROOT="${HOME}/.config/broot/launcher/bash/br"
[ -f ${BROOT} ] && source ${BROOT}


autoload -U bashcompinit
bashcompinit


if which pipx > /dev/null; then
  source "${HOME}/src/dotfiles/completions/_pipx"
fi

if which goenv > /dev/null; then
  source "${HOME}/src/dotfiles/completions/_goenv"
fi

if which rbenv > /dev/null; then
  source "${HOME}/src/dotfiles/completions/_rbenv"
fi

if which fnm > /dev/null; then
  source "${HOME}/src/dotfiles/completions/_fnm"
fi

if which cz > /dev/null; then
  source "${HOME}/src/dotfiles/completions/_cz"
fi

if which mcfly > /dev/null; then
  source "${HOME}/src/dotfiles/completions/_mcfly"
fi

function gam() { "/Users/johno/bin/gam/gam" "$@" ; }

# Remove unwanted _mtools completion (breaks my 'mcd' alias)
compdef -d mcd

# To customize prompt, run `p10k configure` or edit ~/.p10k.zsh.
[[ ! -f ~/.p10k.zsh ]] || source ~/.p10k.zsh
