# Enable Powerlevel10k instant prompt. Should stay close to the top of ~/.zshrc.
# Initialization code that may require console input (password prompts, [y/n]
# confirmations, etc.) must go above this block; everything else may go below.
if [[ -r "${XDG_CACHE_HOME:-$HOME/.cache}/p10k-instant-prompt-${(%):-%n}.zsh" ]]; then
  source "${XDG_CACHE_HOME:-$HOME/.cache}/p10k-instant-prompt-${(%):-%n}.zsh"
fi

# Source Prezto.
if [[ -s "${ZDOTDIR:-$HOME}/.zprezto/init.zsh" ]]; then
  source "${ZDOTDIR:-$HOME}/.zprezto/init.zsh"
fi

# By default, ^S freezes terminal output and ^Q resumes it. Disable that so
# that those keys can be used for other things.
unsetopt flowcontrol

# Put any host-specific config in ~/.zshrc.local
if [[ -s "${ZDOTDIR:-$HOME}/.zshrc.local" ]]; then
  source "${ZDOTDIR:-$HOME}/.zshrc.local"
fi

if [[ $TERM == 'cons25' || $TERM == 'linux' || $ITERM_PROFILE == 'Light' || $ITERM_PROFILE == 'Sidebar' ]]; then
  true  # Console session or 'demo mode', so not starting tmux
else
  if [[ $TMUX != "" ]]; then
    true    # Tmux/screen already running, so not starting a nested session
  else
    if which tmux > /dev/null; then
      if [[ -r ~/.tmux.conf ]]; then
        tmux -f ~/.tmux.conf attach
      else
        # ...otherwise just start a default tmux session
        tmux new -s "$(hostname -s)/$(basename $(pwd))"
      fi
    fi
  fi
fi

function gam() { "/Users/johno/bin/gam/gam" "$@" ; }

# To customize prompt, run `p10k configure` or edit ~/.p10k.zsh.
[[ ! -f ~/.p10k.zsh ]] || source ~/.p10k.zsh
